### ISSUE TITLE
Workaround - TS build errors

### ISSUE THREAD

**Issue by lholota** [jorgecotillo/angular2-identity-server4-aspnetcore-template#1]
I tried to download the template and simply building it didn't work. I got errors that node typings couldn't be found, that require and process are undefined. 

Got help from here: https://github.com/angular/angular/issues/17800
Locked typescript at version 2.3.4. Just thought you might want to add this to your readme, otherwise thanks for the template :)

**Comment by jorgecotillo** [comment]
@lholota thanks for the feedback! I'll definitely include it!

**Comment by jorgecotillo** [comment]
Closing issue, added typescript version.
